### ISSUE TITLE
dataset please!

### ISSUE THREAD

**Issue by dragen1860** [pritamqu/AVCAffe#1]
Dear all:  
   thanks for publilshing such a insightful work. I am looking forward to download the dataset and reproduce your work. Please release the dataset as soon as possible.

**Comment by pritamqu** [comment]
Hi - my apology for the late response, for some reason I was not getting any notifications while an issue was created.
to answer your question, it should be anytime soon.

**Comment by pritamqu** [comment]
the dataset is released. sorry for being late and thanks for your interest.
